'use client';

import { useEffect, useMemo, useState } from 'react';
import { collection, getDocsFromServer, query, where } from 'firebase/firestore';
import { db } from '@/lib/firebase';
import { getStoredCustomerMobile } from '@/lib/clientOnboarding';
import Header from '@/components/layout/Header';
import Footer from '@/components/layout/Footer';

type Subscription = Record<string, unknown> & { id: string };
type ActualDelivery = Record<string, unknown> & { id: string };
type CalendarEvent = { date: string; kind: 'upcoming' | 'actual'; status: string; productName: string; quantity: number; subscriptionId?: string; orderId?: string; deliveryNumber?: number };

function parseDate(value: unknown): Date | null {
  if (!value) return null;
  if (value instanceof Date) return Number.isNaN(value.getTime()) ? null : value;
  if (typeof value === 'object') { const v = value as { toDate?: () => Date; seconds?: number }; if (typeof v.toDate === 'function') return v.toDate(); if (typeof v.seconds === 'number') return new Date(v.seconds * 1000); }
  const s = String(value); const d = /^\d{4}-\d{2}-\d{2}$/.test(s) ? new Date(`${s}T00:00:00`) : new Date(s); return Number.isNaN(d.getTime()) ? null : d;
}
function dateOnly(value: unknown) { const d = parseDate(value); return d ? `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}` : ''; }
function addDays(iso: string, days: number) { const d = parseDate(iso); if (!d) return ''; d.setDate(d.getDate()+days); return dateOnly(d); }
function monthTitle(date: Date) { return date.toLocaleDateString('en-IN', { month: 'long', year: 'numeric' }); }
function longDate(value: unknown) { const d = parseDate(value); return d ? d.toLocaleDateString('en-IN', { weekday:'long', day:'2-digit', month:'long', year:'numeric' }) : '—'; }
function statusLabel(status: string) { return status.replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase()); }
function statusClass(status: string) { return ['failed','cancelled'].includes(status.toLowerCase()) ? 'status' : status.toLowerCase() === 'delivered' ? 'status' : 'status upcoming'; }
function futureEventsForMonth(subscriptions: Subscription[], year: number, month: number): CalendarEvent[] {
  const start=dateOnly(new Date(year,month,1)), end=dateOnly(new Date(year,month+1,0)); const events: CalendarEvent[]=[];
  for(const sub of subscriptions){ if(!['active','paused'].includes(String(sub.status??'').toLowerCase())) continue; let next=dateOnly(sub.nextDeliveryDate); const endDate=dateOnly(sub.endDate); let remaining=Math.max(0,Number(sub.totalDeliveries??0)-Number(sub.deliveriesGenerated??0)); if(!next||!remaining) continue;
    for(let i=0;i<remaining&&next&&next<=endDate;i++){ if(next>=start&&next<=end) events.push({date:next,kind:'upcoming',status:'upcoming',productName:String(sub.productName||'Subscription'),quantity:Number(sub.quantity||1),subscriptionId:sub.id}); if(next>end) break; next=addDays(next,7); }
  } return events;
}
function actualEventsForMonth(deliveries: ActualDelivery[], year:number, month:number): CalendarEvent[]{ const start=dateOnly(new Date(year,month,1)), end=dateOnly(new Date(year,month+1,0)); return deliveries.map(d=>({date:dateOnly(d.deliveryDate),kind:'actual' as const,status:String(d.status||'assigned'),productName:String(d.productName||'Subscription'),quantity:Number(d.quantity||1),subscriptionId:String(d.subscriptionId||''),orderId:String(d.orderId||''),deliveryNumber:Number(d.deliveryNumber||0)})).filter(e=>e.date>=start&&e.date<=end); }

export default function DeliveryCalendarPage(){
  const [subscriptions,setSubscriptions]=useState<Subscription[]>([]); const [deliveries,setDeliveries]=useState<ActualDelivery[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [signedOut,setSignedOut]=useState(false); const [view,setView]=useState(()=>new Date());
  useEffect(()=>{ let alive=true; const load=async()=>{ const mobile=getStoredCustomerMobile(); if(!mobile){if(alive){setSignedOut(true);setLoading(false);}return;} try{ const [ss,ds]=await Promise.all([getDocsFromServer(query(collection(db,'subscriptions'),where('customerId','==',mobile))),getDocsFromServer(query(collection(db,'subscriptionDeliveries'),where('customerId','==',mobile)))]); if(!alive)return; setSubscriptions(ss.docs.map(d=>({id:d.id,...d.data()}) as Subscription).filter(s=>String(s.customerId??'').replace(/\D/g,'')===mobile)); setDeliveries(ds.docs.map(d=>({id:d.id,...d.data()}) as ActualDelivery).filter(d=>String(d.customerId??'').replace(/\D/g,'')===mobile)); }catch(e){if(alive)setError(e instanceof Error?e.message:'Unable to load delivery calendar.');}finally{if(alive)setLoading(false);}}; void load(); return()=>{alive=false;};},[]);
  const events=useMemo(()=>{ const a=actualEventsForMonth(deliveries,view.getFullYear(),view.getMonth()); const f=futureEventsForMonth(subscriptions,view.getFullYear(),view.getMonth()); return [...a,...f].sort((x,y)=>x.date.localeCompare(y.date)||(x.kind==='actual'?-1:1)); },[deliveries,subscriptions,view]);
  const cells=useMemo(()=>{const cells:React.ReactNode[]=[]; const first=new Date(view.getFullYear(),view.getMonth(),1); const offset=(first.getDay()+6)%7; const days=new Date(view.getFullYear(),view.getMonth()+1,0).getDate(); const byDate=new Map<string,CalendarEvent[]>(); events.forEach(e=>byDate.set(e.date,[...(byDate.get(e.date)||[]),e])); for(let i=0;i<offset;i++)cells.push(<div className="calendar-empty" key={`e-${i}`}/>); for(let day=1;day<=days;day++){const iso=`${view.getFullYear()}-${String(view.getMonth()+1).padStart(2,'0')}-${String(day).padStart(2,'0')}`;const es=byDate.get(iso)||[];cells.push(<div className={`calendar-cell ${es.length?'calendar-date':''}`} key={iso}><b>{day}</b>{es.slice(0,3).map((e,i)=><div className="calendar-event" key={`${iso}-${i}`}><span className={statusClass(e.status)}>{e.kind==='upcoming'?'UPCOMING':statusLabel(e.status)}</span><div className="calendar-event-name">{e.productName}</div></div>)}{es.length>3&&<div className="muted calendar-more">+{es.length-3} more</div>}</div>);} return cells;},[events,view]);
  const eventRows=events.map((e,i)=><div className="order-row" key={`${e.date}-${e.kind}-${i}`}><div><strong>{longDate(e.date)}</strong><div className="order-meta">{e.productName} · Qty {e.quantity}{e.deliveryNumber?` · Delivery #${e.deliveryNumber}`:''}</div></div><span className={statusClass(e.status)}>{e.kind==='upcoming'?'UPCOMING':statusLabel(e.status)}</span></div>);
  return <><Header navItems={[]} /><main className="section"><div className="container"><div className="account-shell"><aside className="account-side"><a href="/account">◉ Overview</a><a href="/orders">▣ My Orders</a><a href="/subscriptions">↻ My Subscriptions</a><a className="active" href="/delivery-calendar">◫ Delivery Calendar</a><a href="/addresses">⌂ My Addresses</a><a href="/profile">◎ My Profile</a></aside><section className="account-main">
    {loading&&<><div className="account-title"><div><div className="eyebrow">Subscription delivery</div><h1>Delivery Calendar</h1><p className="muted">Loading your delivery schedule…</p></div><span className="status upcoming">LOADING</span></div><div className="panel"><p className="muted">Loading your delivery schedule…</p></div></>}
    {!loading&&signedOut&&<><div className="account-title"><div><div className="eyebrow">Subscription delivery</div><h1>Delivery Calendar</h1><p className="muted">Sign in to view your delivery schedule.</p></div></div><div className="panel"><h3>Sign in to continue</h3><p className="muted">There are no customer deliveries to display until you sign in.</p><a className="btn primary" href="/account">Go to Account</a></div></>}
    {!loading&&!signedOut&&error&&<><div className="account-title"><div><div className="eyebrow">Subscription delivery</div><h1>Delivery Calendar</h1><p className="muted">Unable to load your delivery schedule.</p></div></div><div className="panel"><p className="muted">{error}</p></div></>}
    {!loading&&!signedOut&&!error&&!subscriptions.length&&!deliveries.length&&<><div className="account-title"><div><div className="eyebrow">Subscription delivery</div><h1>Delivery Calendar</h1><p className="muted">Your scheduled subscription deliveries will appear here.</p></div><span className="status">NO ACTIVE PLAN</span></div><div className="panel"><h3>No active subscription</h3><p className="muted">There are no scheduled subscription deliveries for this customer.</p><a className="btn primary" href="/microgreens">Shop Fresh</a></div></>}
    {!loading&&!signedOut&&!error&&(subscriptions.length||deliveries.length)>0&&<><div className="account-title"><div><div className="eyebrow">Subscription delivery</div><h1>Delivery Calendar</h1><p className="muted">Browse your subscription delivery history and upcoming schedule.</p></div><span className="status upcoming">{subscriptions.length} SUBSCRIPTION{subscriptions.length===1?'':'S'}</span></div><div className="panel"><div className="calendar-head"><button className="btn" type="button" aria-label="Previous month" onClick={()=>setView(new Date(view.getFullYear(),view.getMonth()-1,1))}>←</button><h3 style={{margin:0}}>{monthTitle(view)}</h3><button className="btn" type="button" aria-label="Next month" onClick={()=>setView(new Date(view.getFullYear(),view.getMonth()+1,1))}>→</button></div><div className="calendar-grid"><div className="day-name">Mon</div><div className="day-name">Tue</div><div className="day-name">Wed</div><div className="day-name">Thu</div><div className="day-name">Fri</div><div className="day-name">Sat</div><div className="day-name">Sun</div>{cells}</div><div className="delivery-actions"><span className="status upcoming">● Upcoming</span><span className="status">● Actual delivery</span></div></div><div className="panel"><h3>Deliveries in {monthTitle(view)}</h3>{eventRows.length?eventRows:<p className="muted">No deliveries scheduled or recorded for this month.</p>}</div></>}
  </section></div></div></main><Footer navItems={[]} settings={null}/></>;
}
